language: r

sudo: required

script:
# in the next step we use pdflatex to convert .tex to .pdf
# of course we could use pandoc for this also, but pdflatex generates nicer PDFs
  - cd lectures; pdflatex -interaction=nonstopmode main.tex; pdflatex -interaction=nonstopmode main.tex

apt_packages:
# we download pdf2djvu to also generate a djvu file of our LaTeX source
  - texlive-latex-extra
  - texlive-pictures

deploy:
  provider: releases
  api_key:
    secure: "O/0KcQXZag2JrbwqaQCNUbJ+2PLxVWOoiwnQuOmxPAneyFHA1V0SgXKvTGIIfwRIK7YslIoEFSgItbhNpP3nZdn+bfqhNtsmG+YE+BATFEJNWnsSz2fhfdKzbn+A89jdgkds2dZW8dAlmAF/S0ZIIp4njDWl33J+TkVq8fUgNzCyfmkWq0YyIJ5hGiW3ue/+BEe9NToQfwRmYBr9BHhPRlV9/UbFaLIhtxngchj4r8OwSbq0h+zmTgAHrSr02tX3wEC8S3UBMF/j7X1eiEUci5Baht6JFBMVPfKeNxQUevAiaFkQsaFN78ihRvRDM8vDvtQOw0ZMo4J4y6nHZwOe9KEnqT1BiHsJKBZsYMppxlkccelwvV2mFmc9Z9iwycjCImhMtjC/T4i+9nLZEtIKVyILHwM9C5gCpNksLW8r47wgsWL41TZxlwMcAxIkL81vYYo4IKJjEO07PUTMnwOyOoMfuKoRxD4x04INfxWLimcvOvwPHfU0+Os4UBcMNb0ZXywH2hhXutZf/stWOy46vAOBE3UMSktkMTGwVEw0VmPtFK0tserljdYyehDLzS93GWOL4B05Z2b6sGOUHayrmEOJQWA0FVVN4S5vBu1ZY3p7msdHq2Frr95nTHXOQ3p9QgqbgR7p/hPHyQwDo3mW2ll15cZI2N26HKGJGEKwZoI="
  file:
    - "main.pdf"
  skip_cleanup: true
  overwrite: true
  on:
    repo: srossd/PTI-CS-103

notifications:
  email: false
