language: r

sudo: required

script:
# in the next step we use pdflatex to convert .tex to .pdf
# of course we could use pandoc for this also, but pdflatex generates nicer PDFs
  - cd lectures; pdflatex -interaction=nonstopmode main.tex; pdflatex -interaction=nonstopmode main.tex

apt_packages:
# we download pdf2djvu to also generate a djvu file of our LaTeX source
  - texlive-latex-extra

deploy:
  provider: releases
  api_key:
    secure: "ZJruTEk1OV7mBLN0hAE0zoKBIpbZlgIm5pyVcxpmgnX5YTfery6VupLbnF+IaYSknzR5MFLIENmxEFT0K4a5wFADyaXjP9o//R2706Ec/lXlaW7DT1vhc7ZR8Mfw13nuPPqq5ZOZj/h1sOGJJnY0d1j9GhPIPpcP1rTLRUz9pvvphKad3zwKKlMSukaQ2i8437VnZL5j5JxC5a1UuT/xPq6FNc4y0z36LsAKVD8Uik8lJGuIgjxJLLZmONaxZrTiGFWruL5rI7q3O+vMb5Y57b8fSWfzSbBBhQpu7tLG3t9PAs8vIm73/Qbg07f5H6w7ev5yy4pKQdLK3tdT/mW2QzuRf3MLsdZTQLYbIsyvbxzJwuLbFWQixAcn4z/SbhzAd1FDnHnJGsiEhhw8LGZWAG7c9DlMHa+ra6qBKqEA9WkR8b6HYrTMOgo0L0diPzQ62m6krr9VX8eF5+kvIaclomaHyNUg0R03qzN7pu6f/FDGEHAHvgakF1H2iEDcW1NOI/GttAlJEg1CP/DsjKHpIeMb3YF9gtkt2PuOLWVRudFhLCOlaw/HrvGUyrFcBuKHhDtPP4xHvM5wQwzitB4gSLpwpgB5W5EXGd5E6VvCa2rjz1H9ju15xl0zuPBnGVIKD8zmjHKq9/FXCxkJqg77nD8KOQ3wV1AWLhXOmihJ7u8="
  file:
    - "main.pdf"
  skip_cleanup: true
  overwrite: true
  on:
    repo: srossd/PTI-CS-103

notifications:
  email: false
